apiVersion: v1
kind: Secret
metadata:
  name: nginx-credentials
  namespace: dev
type: Opaque
data:
  username: YWRtaW4=
  password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-credentials
  namespace: test
type: Opaque
data:
  username: YWRtaW4=
  password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-credentials
  namespace: prod
type: Opaque
data:
  username: YWRtaW4=
  password: cGFzc3dvcmQ=
